### ISSUE TITLE
Unable to render captcha for multiple forms on a single page

### ISSUE THREAD

**Issue by apoorvaeternity** [torchbox/django-recaptcha#141]
I have multiple user registration forms on a single page. The captcha is getting rendered for only first form on the page and not for others.

**Comment by egorsmkv** [comment]
See that answer -- https://stackoverflow.com/a/28126317/5707560

**Comment by egorsmkv** [comment]
Or you can use https://github.com/kbytesys/django-recaptcha2

See the example: https://github.com/kbytesys/django-recaptcha2#multiple-render-example

**Comment by benzkji** [comment]
In my case, it's rendered many times, but only the first works correctly. Will investigate.

**Comment by thibaudcolas** [comment]
Same question as #75.
