### ISSUE TITLE
Recaptcha not Working on Mobile (Chrome Browser)

### ISSUE THREAD

**Issue by thaxy** [torchbox/django-recaptcha#155]
Hi,

I am using ``Django==2.0.2`` and ``django-recaptcha==1.4.0`` on my aunt's website.
While everything works fine for the desktop environment I am struggeling to see the captcha with the mobile browser (chrome 66.0.3359.158) on my phone. I even tried to remote debug the website but couldn't see any error or warning messages.

Could you guys give me a hint how to tackle this problem?
Website: https://marleneschulz.info/kontakt/

____

I am rendering the single field within my ``template.html`` with ``{{ form.captcha }}``.

**Comment by thibaudcolas** [comment]
I would expect this was a fluke if it’s only been reported once, so will close this now.
