### ISSUE TITLE
ReCAPTCHA validation failed due to: ['timeout-or-duplicate']

### ISSUE THREAD

**Issue by rickey-g** [torchbox/django-recaptcha#183]
We get a lot of errors: "ReCAPTCHA validation failed due to: ['timeout-or-duplicate']"

Is there anyway to silence this error message?
Or can it be changed to a debug log? 
As this just happens sometimes and our errors logs get filled with it.

**Comment by CrazyPilot** [comment]
Having this error when some spam bots are trying to submit forms on my website. Also having `ReCAPTCHA validation failed due to: ['incorrect-captcha-sol']`

**Comment by jeroen-80** [comment]
Same here, seeing this message in logs since some weeks. Running django-recaptcha==2.0.2.

**Comment by alexalligator** [comment]
We are also seeing this problem. I believe it is linked to fact that response tokens are only valid for 2 minutes.
See Google docs [here](https://developers.google.com/recaptcha/docs/verify?hl=en#token_restrictions).

To reproduce:
1. Load your page with the recaptcha v3 form
2. Wait two minutes
3. Submit the form
4. Look for `ReCAPTCHA validation failed due to: ['timeout-or-duplicate']` in your logs

**Comment by hoenie-ams** [comment]
Actually getting this error for valid form submissions.

**Comment by Gromph** [comment]
For a quickie fix I overrode templates/captcha/includes/js_v3.html and fixed up to update every 110 seconds:

```html
<script src="https://{{ recaptcha_domain }}/recaptcha/api.js?render={{ public_key }}{% if api_params %}&{{ api_params }}{% endif %}"></script>
<script type="text/javascript">

    function updateCaptcha() {
      grecaptcha.execute('{{ public_key }}', {action: 'form'})
        .then(function(token) {
            console.log("reCAPTCHA validated for 'data-widget-uuid=\"{{ widget_uuid }}\"'. Setting input value...")
            var element = document.querySelector('.g-recaptcha[data-widget-uuid="{{ widget_uuid }}"]');
            element.value = token;
        });
    }

    grecaptcha.ready(function() {
      updateCaptcha();
      setInterval(updateCaptcha, 110000)
    });
</script>
```

**Comment by oesah** [comment]
@Gromph I cannot override the templates for some odd reason. Did exactly, what you suggest but it still uses to template from the pip module. It's weird, because I am overriding lots of other templates from other third-party libs, just this one seems to be ignored. Did you encounter a similar issue?

**Comment by Gromph** [comment]
@oesah Looks like what I did was make an app called "plaza-django-recaptcha":
```
INSTALLED_APPS = [
	"plaza-django-recaptcha", # must be before "captcha" to override js_v3.html
	"captcha",
]
```

Then the app has just these 2 files:
```
plaza-django-recaptcha\__init__.py
plaza-django-recaptcha\templates\captcha\includes\js_v3.html
```

**Comment by jimkring** [comment]
just installed django-recaptcha and noticing this error -- it appears that the error was a spammer account, but it would be nice if this doesn't raise a server error. Any thoughts on an official fix from the dev team?

**Comment by Andrew-Chen-Wang** [comment]
Anyone have one for v2 checkbox? This is what I've currently done, but I'm getting some console errors:
```html
<script src="https://{{ recaptcha_domain }}/recaptcha/api.js{% if api_params %}?{{ api_params }}{% endif %}"></script>
<script type="text/javascript">
  grecaptcha.ready(function() {
    function updateCaptcha() {
      grecaptcha.reset("{{ widget_uuid }}")
    }
    setInterval(updateCaptcha, 110000)
  });
</script>
```

**Comment by fjsj** [comment]
This is not actually a server error, AFAIK. This is only a logging.error message. Sentry (and others) do detect this as an error. I think the fix should be changing the severity of this message to warning on this library.

**Comment by plumber-craic** [comment]
> For a quickie fix I overrode templates/captcha/includes/js_v3.html and fixed up to update every 110 seconds:
> 
> ```
> <script src="https://{{ recaptcha_domain }}/recaptcha/api.js?render={{ public_key }}{% if api_params %}&{{ api_params }}{% endif %}"></script>
> <script type="text/javascript">
> 
>     function updateCaptcha() {
>       grecaptcha.execute('{{ public_key }}', {action: 'form'})
>         .then(function(token) {
>             console.log("reCAPTCHA validated for 'data-widget-uuid=\"{{ widget_uuid }}\"'. Setting input value...")
>             var element = document.querySelector('.g-recaptcha[data-widget-uuid="{{ widget_uuid }}"]');
>             element.value = token;
>         });
>     }
> 
>     grecaptcha.ready(function() {
>       updateCaptcha();
>       setInterval(updateCaptcha, 110000)
>     });
> </script>
> ```

I had multiple v3 widgets, and found that only the initial widget uuid was being used. This fixed it for me:
```
<script src="https://{{ recaptcha_domain }}/recaptcha/api.js?render={{ public_key }}{% if api_params %}&{{ api_params }}{% endif %}"></script>
<script type="text/javascript">
    var i = 0;
    var widgetUUIDs = []
    function updateCaptcha(widgetUUID) {
        if (widgetUUID === undefined) {
            j = i % widgetUUIDs.length;
            var widgetUUID = widgetUUIDs[j];
        } else {
            widgetUUIDs.push(widgetUUID);
        }
        i++;
        grecaptcha.execute('{{ public_key }}', {action: 'form'})
        .then(function(token) {
            console.log("reCAPTCHA validated for 'data-widget-uuid=" + widgetUUID + "'. Setting input value...")
            var element = document.querySelector('.g-recaptcha[data-widget-uuid="' + widgetUUID + '"]');
            element.value = token;
        });
    }

    grecaptcha.ready(function() {
      updateCaptcha("{{ widget_uuid }}");
      setInterval(updateCaptcha, 110000)
    });
</script>

```
