### ISSUE TITLE
Future request: ReCaptcha in CreateView

### ISSUE THREAD

**Issue by caniko** [torchbox/django-recaptcha#185]

**Comment by AltusBarry** [comment]
Hey @caniko2, django-recaptcha should already be working on CreateViews. 
django-recatpcha is simply an extra form field one can make use of and it does not, for the most part, matter what underlying view/form is used.

If you are experiencing issues with the recaptcha field on the CreateView, we would guess it has to do with the saving of the form's instance. If this is indeed the issue, we suggest removing the recaptcha field from the cleaned data after it has been validated.
