### ISSUE TITLE
urlopen error [Errno 111] Connection refused

### ISSUE THREAD

**Issue by Zalkota** [torchbox/django-recaptcha#191]
Both of my sites are experiencing this issue:

Internal Server Error: /contact/
Exception Type: URLError at /contact/
Exception Value: <urlopen error [Errno 111] Connection refused>

timeout=getattr(settings, "RECAPTCHA_VERIFY_REQUEST_TIMEOUT", 10)

They were working in the past.

**Comment by daniele-nicastro** [comment]
Do you use RECAPTCHA_PROXY in settings.py?
Removing maybe helps.
