### ISSUE TITLE
china accessibility

### ISSUE THREAD

**Issue by clashthe** [torchbox/django-recaptcha#206]
after putting
`RECAPTCHA_DOMAIN = 'www.recaptcha.net'`
in settings.py, captcha field is still inaccessible

**Comment by imrbg** [comment]
i also tried to set
`RECAPTCHA_PROXY = {'http': 'socks5://127.0.0.1:1080', 'https': 'socks5://127.0.0.1:1080'}
`
but no luck

**Comment by thibaudcolas** [comment]
This is two years old without any additional reports so I’ll assume it might be a one-off. If others are having the same issue I’ll gladly reopen the issue – please provide further info so we can investigate.
