### ISSUE TITLE
Not working with IE11 

### ISSUE THREAD

**Issue by salvorapi** [torchbox/django-recaptcha#219]
If you use Internet Explorer 11 and try to visite a page that use invisibile  widget then it doesn't work.

**Comment by matmunn** [comment]
You need to polyfill Element.closest for IE11: https://developer.mozilla.org/en-US/docs/Web/API/Element/closest#Polyfill

**Comment by thibaudcolas** [comment]
Thank you, I’ve added a note to the README that this package doesn’t support IE11.
