### ISSUE TITLE
v2.0.6 tarball not on PyPI

### ISSUE THREAD

**Issue by atodorov** [torchbox/django-recaptcha#222]
Do you mind uploading the 2.0.6 tar.gz file to PyPI alongside the wheel package ? Not everyone wants to use wheels.

**Comment by thibaudcolas** [comment]
@atodorov yep, it’s annoying this is missing. I will close this issue now without adding the tarball – even though technically we could, I don’t want people’s existing installs to potentially be tripped up by the addition of another artifact for an existing release.

You can expect future releases to be sdist + wheel.
