### ISSUE TITLE
V3 - verify on submit event, not page load

### ISSUE THREAD

**Issue by bendavis78** [torchbox/django-recaptcha#223]
Ideally the V3 captcha should be verified on submit, not page load, so that the token does not time out. Is there a way configure this?

**Comment by oesah** [comment]
I have the same issue :( Getting timeout errors on Sentry.

**Comment by nicksergeant** [comment]
Same. Even though I have JS that re-verifies the captcha every so often, if the user is on a mobile phone and comes back to the same page hours or days later, often times that `setInterval` loop is broken and they'll get a spam failure when submitting.

**Comment by enzedonline** [comment]
I see #296 was merged, but the recaptcha still verifies on page load for V3 rather than submit.
I load the recaptcha with `fields[self.CAPTCHA_FIELD_NAME] = ReCaptchaField(label="", widget=ReCaptchaV3())` in the form builder.
I'm using v3.0.0
Anything I'm missing to fix this?

**Comment by Stormheg** [comment]
Hey @enzedonline, #296 was merged but hasn't made it into a release yet. We are working on getting a new release out, see https://github.com/torchbox/django-recaptcha/pull/312.

We should probably close this now that #296 is merged.

**Comment by enzedonline** [comment]
@Stormheg Great! Thanks for that.
