### ISSUE TITLE
Release with deprecation fixes

### ISSUE THREAD

**Issue by tbrlpld** [torchbox/django-recaptcha#243]
Django 4.0 is due to be released soon. The `ugettext...` aliases which are still used in the latest release (2.0.6) of this package will be removed in Django 4.0. 

Running with deprecation warnings turned on (`python -Wa`) you will also see this: 
```
/venv/lib/python3.8/site-packages/captcha/fields.py:26: RemovedInDjango40Warning: django.utils.translation.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy().
```

The fix for this issue has already been merged to `master` about a year ago with #224. 

It would be greatly appreciated if there would be a new release to incorporate these changes 🙏

**Comment by ptibom** [comment]
Django 4.0 has been out a while now and this deprecation indeed breaks it.

**Comment by Andrew-Chen-Wang** [comment]
Hi all, just published django-recaptcha429 with updated support and removal of upper Django constraint. https://github.com/Andrew-Chen-Wang/django-recaptcha429

I will not have time to make full commitment, but I will take a look at all PRs for potential merge. Cheers.

**Comment by Andrew-Chen-Wang** [comment]
I know longer see deprecation warnings (as we have upgraded to 4.0 now). Closing.
