### ISSUE TITLE
Better way to validate recaptcha keys

### ISSUE THREAD

**Issue by fedemotta** [torchbox/django-recaptcha#26]
When I tried to load a form using recaptcha and no keys were added to the settings file the following error have been thrown:
"Captcha: Input error: k: Format of site key was invalid"

I would like to have a server error (or something similar) if there are invalid keys. The general idea is to avoid showing this error to the user if we miss the keys in the deployment process or there are invalid keys.

Thanks

**Comment by thibaudcolas** [comment]
I can see django-recaptcha uses Django’s system check framework for this (https://github.com/torchbox/django-recaptcha/blob/main/captcha/checks.py), so I’ll assume this issue is out of date and close it now.
