### ISSUE TITLE
Why There is Still a Label for Captcha When I Use ReCaptchaV3?

### ISSUE THREAD

**Issue by ttxs25830** [torchbox/django-recaptcha#280]
![](https://user-images.githubusercontent.com/57991009/172041835-048fb2a3-0417-4c77-be57-9d7bebb74b91.png)
I think when we use ReCaptchaV3, there should't a label to show where the captcha is. 
Is it a bug? Or is there a reason that we should still render a label?

**Comment by Andrew-Chen-Wang** [comment]
probably just a bug

**Comment by mrxsal** [comment]
You can just render the label as an empty string:
`captcha = ReCaptchaField(widget=ReCaptchaV3, label='')`

**Comment by Stormheg** [comment]
Hi, I just merged #294 that fixes this by having the ReCaptchaV3 widget output a hidden field, which omits the label.

The fix will be included in the next release!
