### ISSUE TITLE
Do not hardcode protocol in API_SERVER setting

### ISSUE THREAD

**Issue by chrisspen** [torchbox/django-recaptcha#31]
In client.py, you hardcode the http and https protocol in the URLs for the recaptcha URL. This is generally bad practice, since this protocol should almost always match the parent page. It's also unnecessary since the protocol is optional for includes. 

By default, your configuration will not seamlessly work for SSL pages. 

However, if you simply define:

```
DEFAULT_API_SERVER = DEFAULT_API_SSL_SERVER = '//www.google.com/recaptcha/api'
```

that should work for 99.99% of users for both SSL and non-secure pages without any special configuration.

**Comment by thibaudcolas** [comment]
It looks like the requests are currently hard-coded to HTTPS, which seems sensible to me, so I’ll close this now.
