### ISSUE TITLE
Html validation

### ISSUE THREAD

**Issue by codefisher** [torchbox/django-recaptcha#55]
This is kind of nit-picking.  But I have a project that should render valid HTML, and the html in the default template does not do that.  Easy enough to over ride the template, but I thought maybe you could also change it.
The problem is the two ampersands in the urls need to be changed from & to &amp; and the attribute frameborder="0" in the iframe should be changed to style="border:0;"

**Comment by sschoorens** [comment]
scrolling="no" is obselete too, also the value="" in the textarea is invalid.

**Comment by thibaudcolas** [comment]
Even though this issue is older, I’ll close it as a dupe of #212, which has more details / workarounds.
