### ISSUE TITLE
If AJAX option is True - attrs don't work

### ISSUE THREAD

**Issue by elky** [torchbox/django-recaptcha#60]
When I do this `CAPTCHA_AJAX = True` in my settings - reCaptcha widget looses all attrs like theme or language.

**Comment by gurk** [comment]
I've tested this pull request, deserves to be merged IMO.

**Comment by letoss** [comment]
I need this fix too! When will be merged?

**Comment by thibaudcolas** [comment]
I can’t see `CAPTCHA_AJAX` in the code anymore so will assume this is no longer relevant.
