### ISSUE TITLE
Problem with validation in captcha.client

### ISSUE THREAD

**Issue by martin-sicho** [torchbox/django-recaptcha#78]
Hi,
I think I have found a minor bug in [client.py](https://github.com/praekelt/django-recaptcha/blob/develop/captcha/client.py) (django-recaptcha version: 1.0.4):

On line 143 it says:

``` python
return_code = return_values[0]
```

and on line 147 `return_code` is checked like this:

``` python
if (return_code == "true"):
        return RecaptchaResponse(is_valid=True)
    else:
        return RecaptchaResponse(is_valid=False, error_code=return_values[1])
```

For me the value of `return_code` is a byte sequence ([bytes](https://docs.python.org/3.1/library/functions.html#bytes)), which caused the condition `return_code == "true"` to always return `False` (I am using Python 3.4.). I made a quick fix by changing line ~~147~~ 143 to:

``` python
return_code = return_values[0].decode('utf-8')
```

This seems to work fine, but there might be a much better solution.

**Comment by mbambafd** [comment]
like this return_code = return_values[0].decode('utf-8') or return_code = return_values[0].decode('utf-8') because in line 147 we have a condition instruction

**Comment by martin-sicho** [comment]
Oh, crap. Sorry, I got the lines mixed up. I changed line **143** to

```python
return_code = return_values[0].decode('utf-8')
```

not line **147**.

This is the complete piece of code working for me at the moment (starting from line **132**)

```python
httpresp = urlopen(req)
    if getattr(settings, "NOCAPTCHA", False):
        data = json.loads(httpresp.read().decode('utf-8'))
        return_code = data['success']
        return_values = [return_code, None]
        if return_code:
            return_code = 'true'
        else:
            return_code = 'false'
    else:
        return_values = httpresp.read().splitlines()
        return_code = return_values[0].decode('utf-8')

    httpresp.close()

    if (return_code == "true"):
        return RecaptchaResponse(is_valid=True)
    else:
        return RecaptchaResponse(is_valid=False, error_code=return_values[1])
```

**Comment by lzanuz** [comment]
Line 134 - data = json.loads(httpresp.read().decode('utf-8'))

'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

on this "httpresp.read()" I got the value:

b'\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\x00\xab\xe6RPP*.MNN-.V\xb2R()*M\xe5\xaa\x05\x009\nb\t\x15\x00\x00\x00'

this value can't be decoded.

NOCAPTCHA = True                                                                 
RECAPTCHA_USE_SSL = True

Any Idea?

**Comment by martin-sicho** [comment]
Maybe try different encoding?

**Comment by MikeVL** [comment]
I have the same problem with Django==1.6.11 and Python==2.7

**Comment by thibaudcolas** [comment]
This bug report is for a very old version so I’ll assume it’s no longer relevant and close – please let me know if not.
