### ISSUE TITLE
nocaptcha template should explicitly render and fire JS event

### ISSUE THREAD

**Issue by opensrcken** [torchbox/django-recaptcha#80]
I had some timing sensitive JS, that needed to know when the nocaptcha field was ready. I wound up virtually copy-pasting the code example from https://developers.google.com/recaptcha/docs/display in the "explicit render" section, and firing a JS event from within the "onload" callback. I don't see a good reason why this shouldn't be the standard template that is used by django-recaptcha.

That way, users could trivially hook into a "captchaFieldReady" JS event without having to customize the template or dig into the weeds of Google's NoCaptcha customization.

If you agree, I'd be happy to submit a PR.

**Comment by thibaudcolas** [comment]
I like the idea but this was proposed so long ago I would expect it’s no longer relevant. Can reopen if it is.
